name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-and-test:
    uses: ./.github/workflows/test.yml
    
  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
          TAG="v$VERSION"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
          TAG=${GITHUB_REF#refs/tags/}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.TAG }}
        name: Prosody ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation
          
          ### Quick Install (Recommended)
          ```bash
          # Clone and install
          git clone https://github.com/${{ github.repository }}.git
          cd prosody && ./install.sh
          ```
          
          ### Manual Install
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd prosody
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install -e .
          ```
          
          ## Running Prosody
          
          ```bash
          # Run in foreground
          prosody
          
          # Run in background  
          prosody &
          
          # Enable auto-start
          systemctl --user enable prosody
          systemctl --user start prosody
          ```
          
          ## What's Changed
          See the full changelog below.