name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-and-test:
    uses: ./.github/workflows/test.yml
    
  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
          TAG="v$VERSION"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
          TAG=${GITHUB_REF#refs/tags/}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
    
    - name: Create source archive
      run: |
        # Create a clean archive without .git directory
        mkdir -p dist
        git archive --format=tar.gz --prefix=prosody-${{ steps.version.outputs.VERSION }}/ \
          -o dist/prosody-${{ steps.version.outputs.VERSION }}.tar.gz HEAD
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.TAG }}
        name: Prosody ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/prosody-${{ steps.version.outputs.VERSION }}.tar.gz
        body: |
          ## Installation
          
          ### Quick Install (Recommended)
          ```bash
          # Download and extract
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.TAG }}/prosody-${{ steps.version.outputs.VERSION }}.tar.gz
          tar -xzf prosody-${{ steps.version.outputs.VERSION }}.tar.gz
          cd prosody-${{ steps.version.outputs.VERSION }}
          
          # Install
          ./install.sh
          ```
          
          ### Alternative: Clone from Git
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd prosody && ./install.sh
          ```
          
          ## Running Prosody
          
          ```bash
          # Run in foreground
          prosody
          
          # Run in background  
          prosody &
          
          # Enable auto-start
          systemctl --user enable prosody
          systemctl --user start prosody
          ```
          
          ## What's Changed
          See the full changelog below.