name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-and-test:
    uses: ./.github/workflows/test.yml
    
  build-deb:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper dh-python python3-all python3-setuptools
        
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version $VERSION"
        
    - name: Update version in files
      run: |
        # Update setup.py
        sed -i "s/version=\".*\"/version=\"${{ steps.version.outputs.VERSION }}\"/" setup.py
        
        # Update debian/changelog
        cat > debian/changelog << EOF
        prosody-stt (${{ steps.version.outputs.VERSION }}-1) stable; urgency=medium
        
          * Release version ${{ steps.version.outputs.VERSION }}
          * See https://github.com/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.VERSION }}
        
         -- ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>  $(date -R)
        EOF
        
    - name: Build Debian package
      run: |
        chmod +x build-deb.sh
        ./build-deb.sh
        
    - name: Test package installation
      run: |
        # Install the package
        sudo dpkg -i dist/*.deb || true
        sudo apt-get install -f -y
        
        # Verify installation
        which prosody
        dpkg -l | grep prosody-stt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: dist/*.deb
        
  create-release:
    needs: build-deb
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: debian-package
        path: dist/
        
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
          TAG="v$VERSION"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
          TAG=${GITHUB_REF#refs/tags/}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.TAG }}
        name: Prosody ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/*.deb
        body: |
          ## Installation
          
          ### Debian/Ubuntu
          ```bash
          # Download the .deb package
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.TAG }}/prosody-stt_${{ steps.version.outputs.VERSION }}-1_all.deb
          
          # Install
          sudo dpkg -i prosody-stt_${{ steps.version.outputs.VERSION }}-1_all.deb
          sudo apt-get install -f  # Fix any missing dependencies
          ```
          
          ### From Source
          ```bash
          pip install git+https://github.com/${{ github.repository }}.git@${{ steps.version.outputs.TAG }}
          ```
          
          ## What's Changed
          See the full changelog below.